USE [master]
GO

/****** Object:  Database [guide4u]    Script Date: 1/3/2021 3:20:03 PM ******/
CREATE DATABASE [guide4u]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'guide4u', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\guide4u.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'guide4u_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\guide4u_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [guide4u].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [guide4u] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [guide4u] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [guide4u] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [guide4u] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [guide4u] SET ARITHABORT OFF 
GO

ALTER DATABASE [guide4u] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [guide4u] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [guide4u] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [guide4u] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [guide4u] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [guide4u] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [guide4u] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [guide4u] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [guide4u] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [guide4u] SET  DISABLE_BROKER 
GO

ALTER DATABASE [guide4u] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [guide4u] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [guide4u] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [guide4u] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [guide4u] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [guide4u] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [guide4u] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [guide4u] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [guide4u] SET  MULTI_USER 
GO

ALTER DATABASE [guide4u] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [guide4u] SET DB_CHAINING OFF 
GO

ALTER DATABASE [guide4u] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [guide4u] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [guide4u] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [guide4u] SET QUERY_STORE = OFF
GO

ALTER DATABASE [guide4u] SET  READ_WRITE 
GO

