use guide4u;

drop table Travellers;
create table Travellers (
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	password VARCHAR(6),
	dateOfBirth  VARCHAR(14),
	gender VARCHAR(6),
	country VARCHAR(14),
	city VARCHAR(50),
	phoneNumber VARCHAR(50),
	language1 VARCHAR(50),
	language2 VARCHAR(50),
	language3 VARCHAR(50),
	travelStyle1 VARCHAR(13),
	travelStyle2 VARCHAR(13),
	travelStyle3 VARCHAR(13),
	about VARCHAR(59),
	mail VARCHAR(3)
);
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Prescott', 'Smurfit', 'psmurfit0@google.co.uk', 'ewq789', '4/2/1998', 'Male', 'United Kingdom', 'Washington', '202-303-0865', 'Croatian', null, null, 'Adventure', null, null, 'I Love Travels and meeting people from all around the world', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Lucy', 'Velasquez', 'lvelasquez1@1688.com', 'zxd123', '3/23/1998', 'Female', 'Israel', 'H?sselby', '794-916-0611', 'Croatian', null, 'Persian', 'Local Culture', null, 'Sport', 'I Love Travels and meeting people from all around the world', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Eadmund', 'Bruff', 'ebruff2@phpbb.com', 'fgd745', '2/15/1976', 'Male', 'United States', 'Hongtang', '577-524-0429', 'Luxembourgish', 'Malay', null, 'Adventure', 'Local Culture', null, 'I Love Travel <3', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Roarke', 'Viggers', 'rviggers3@google.co.jp', 'zxd123', '5/16/1943', 'Male', 'Israel', 'Paihia', '317-512-8857', 'Arabic', null, 'Lao', 'Art', null, 'Sport', 'I Love Travels and meeting people from all around the world', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Maxine', 'Yele', 'myele4@angelfire.com', 'qwe123', '8/28/1963', 'Female', 'Germany', 'Kavalerovo', '776-665-4207', 'Polish', null, null, 'Nature', null, null, 'I Love Travel <3', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Laurena', 'Keeves', 'lkeeves5@smh.com.au', 'ewq789', '3/23/1995', 'Female', 'United Kingdom', 'Kalynivka', '725-456-5167', 'Portuguese', 'Macedonian', null, 'Art', 'Entertaiment', null, 'Let''s Travel and Rock', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Scarface', 'Edmenson', 'sedmenson6@upenn.edu', 'dfg455', '4/2/1965', 'Female', 'France', 'Panjir', '784-924-2361', 'Amharic', null, 'Georgian', 'Nature', null, 'Adventure', 'Let''s Travel and Rock', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Lucho', 'Duling', 'lduling7@gov.uk', 'dfg455', '6/3/1997', 'Male', 'France', 'Punta Gorda', '941-464-3538', 'Portuguese', 'Norwegian', null, 'Nature', 'Sport', null, 'Let''s Travel and Rock', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Llywellyn', 'Whitnell', 'lwhitnell8@yale.edu', 'ewq789', '9/8/1947', 'Female', 'France', 'Dongtuan', '189-354-1925', 'Kyrgyz', 'Arabic', null, 'Art', 'Entertaiment', null, 'I Love Travels and meeting people from all around the world', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Doralynne', 'Coale', 'dcoale9@gizmodo.com', 'zxd123', '1/1/1950', 'Male', 'United Kingdom', 'Nularan', '518-978-2057', 'Pashto', null, 'Georgian', 'Art', null, 'Adventure', 'I Love Travels and meeting people from all around the world', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Chelsea', 'Zupo', 'czupoa@hud.gov', 'dfg455', '10/13/1979', 'Male', 'Israel', 'Khlong Hat', '904-676-3789', 'Malay', 'Ndebele', 'Oriya', 'Nature', 'Hiking', 'Entertaiment', 'I Love Travels and meeting people from all around the world', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Fredric', 'Strasse', 'fstrasseb@va.gov', 'qwe123', '12/19/1995', 'Male', 'United Kingdom', 'Dongba', '808-565-0995', 'Montenegrin', null, null, 'Local Culture', null, null, 'I Love Travels and meeting people from all around the world', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Rozamond', 'Airy', 'rairyc@sogou.com', 'fgd745', '12/3/2006', 'Female', 'Germany', 'Sirnasari', '816-856-9716', 'Danish', 'Marathi', null, 'Shoping', 'Sport', null, 'Let''s Travel and Rock', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Forrester', 'Maier', 'fmaierd@instagram.com', 'zxd123', '10/1/1998', 'Male', 'United Kingdom', 'Guhuai', '450-757-2738', 'Irish Gaelic', null, 'Irish Gaelic', 'Entertaiment', null, 'Shoping', 'Let''s Travel and Rock', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Nickolai', 'Chamberlen', 'nchamberlene@bloglines.com', 'ewq789', '11/25/1974', 'Male', 'Germany', 'Zhangfang', '369-423-2474', 'Ndebele', 'Dari', 'Croatian', 'Art', 'Adventure', 'Hiking', 'I Love Travel <3', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Prinz', 'Tillett', 'ptillettf@creativecommons.org', 'asd345', '10/21/2007', 'Female', 'Germany', 'Tortosa', '326-702-9120', 'Swati', null, 'Macedonian', 'Entertaiment', null, 'Adventure', 'I Love Travels and meeting people from all around the world', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Augustine', 'Van Haeften', 'avanhaefteng@cdc.gov', 'ewq789', '1/3/2001', 'Female', 'United States', 'Trpinja', '243-577-2437', 'Swati', 'Dutch', null, 'Local Culture', 'Sport', null, 'I Love Travels and meeting people from all around the world', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Granville', 'Giorio', 'ggiorioh@sohu.com', 'qwe123', '10/12/1943', 'Male', 'France', 'Sinegor''ye', '571-463-1448', 'Polish', null, null, 'Local Culture', null, null, 'Let''s Travel and Rock', 'yes');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Giacopo', 'Rosier', 'grosieri@myspace.com', 'fgd745', '12/10/1956', 'Female', 'Germany', 'Cholarg?s', '456-334-6508', 'Marathi', null, 'Quechua', 'Nature', null, 'Sport', 'Let''s Travel and Rock', 'no');
insert into Travellers (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Taryn', 'Shiel', 'tshielj@bing.com', 'qwe123', '4/30/2019', 'Female', 'United States', 'Cergy-Pontoise', '397-415-9558', 'Lithuanian', null, null, 'Shoping', null, null, 'I Love Travels and meeting people from all around the world', 'yes');

drop table LocalGuides;

create table LocalGuides (
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	password VARCHAR(6),
	dateOfBirth  VARCHAR(14),
	gender VARCHAR(6),
	country VARCHAR(14),
	city VARCHAR(50),
	phoneNumber VARCHAR(50),
	language1 VARCHAR(50),
	language2 VARCHAR(50),
	language3 VARCHAR(50),
	travelStyle1 VARCHAR(13),
	travelStyle2 VARCHAR(13),
	travelStyle3 VARCHAR(13),
	about VARCHAR(36),
	mail VARCHAR(3)
);
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Debor', 'Lazer', 'dlazer0@lulu.com', 'dfg455', '13-Jan-1945', 'Female', 'France', 'Ipatinga', '363-957-7443', 'Marathi', null, null, 'Local Culture', null, null, 'Let''s Travel and Rock', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Kamillah', 'Scardefield', 'kscardefield1@bloglines.com', 'qwe123', '09-Sep-1962', 'Male', 'United States', '?elezn? Brod', '505-513-7392', 'Kannada', null, 'Northern Sotho', 'Art', null, 'Entertaiment', 'Come and Travel with me', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Fenelia', 'Ohlsen', 'fohlsen2@businessweek.com', 'dfg455', '27-Mar-1949', 'Female', 'France', 'Gon?b?d', '623-831-3508', 'Korean', null, null, 'Shoping', null, null, 'Come and Travel with me', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Maddy', 'Swateridge', 'mswateridge3@qq.com', 'qwe123', '21-Jul-1984', 'Female', 'United States', 'Bromma', '475-638-8483', 'Kannada', null, 'Gagauz', 'Nature', null, 'Shoping', 'Let''s Travel and Rock', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Archaimbaud', 'Ecob', 'aecob4@paypal.com', 'qwe123', '17-May-2013', 'Female', 'United Kingdom', 'Mayo', '148-464-7557', 'Armenian', null, 'Moldovan', 'Entertaiment', null, 'Sport', 'Come and Travel with me', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Domenic', 'Yitzhakov', 'dyitzhakov5@pbs.org', 'dfg455', '28-Nov-2008', 'Male', 'United States', 'Mabyan', '671-867-4727', 'Somali', null, null, 'Shoping', null, null, 'Let''s Travel and Rock', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Mitzi', 'Just', 'mjust6@networksolutions.com', 'zxd123', '01-Aug-2011', 'Male', 'Germany', 'Hongor', '310-412-3403', 'English', null, null, 'Entertaiment', null, null, 'Come and explore my beatiful country', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Zachery', 'Hizir', 'zhizir7@statcounter.com', 'qwe123', '31-Dec-2008', 'Female', 'Israel', 'Chuangwang', '881-417-2453', 'Persian', null, 'Georgian', 'Shoping', null, 'Hiking', 'Come and Travel with me', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Cal', 'Sevior', 'csevior8@narod.ru', 'qwe123', '02-Dec-1993', 'Male', 'United States', 'El Asintal', '426-705-5585', 'Quechua', 'Luxembourgish', null, 'Art', 'Nature', null, 'Come and explore my beatiful country', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Konstantine', 'Scantleberry', 'kscantleberry9@hao123.com', 'zxd123', '23-Dec-2014', 'Female', 'United Kingdom', 'Donja Dubica', '483-448-1807', 'Greek', null, null, 'Sport', null, null, 'Come and explore my beatiful country', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Freedman', 'Castilljo', 'fcastilljoa@house.gov', 'qwe123', '04-Sep-2018', 'Male', 'Germany', 'Ak’ordat', '219-132-2404', 'Swahili', 'Mongolian', 'Punjabi', 'Hiking', 'Entertaiment', 'Entertaiment', 'Let''s Travel and Rock', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Patsy', 'Tumber', 'ptumberb@hibu.com', 'asd345', '06-Nov-1971', 'Female', 'United Kingdom', 'Colonia Nicolich', '586-695-0940', 'Northern Sotho', null, null, 'Adventure', null, null, 'Let''s Travel and Rock', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Julio', 'Plain', 'jplainc@wikia.com', 'zxd123', '20-Dec-1964', 'Female', 'France', 'Orekhovo-Zuyevo', '388-748-9677', 'Greek', 'Telugu', null, 'Adventure', 'Art', null, 'Come and Travel with me', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Quinlan', 'Icom', 'qicomd@noaa.gov', 'ewq789', '28-Mar-1998', 'Female', 'Israel', 'Bat Khela', '371-363-4744', 'Northern Sotho', null, 'Telugu', 'Entertaiment', null, 'Shoping', 'Come and explore my beatiful country', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Gualterio', 'Bouchard', 'gboucharde@mysql.com', 'ewq789', '25-Apr-1944', 'Female', 'Israel', 'Laval', '614-867-8177', 'Norwegian', 'Albanian', 'Hungarian', 'Shoping', 'Local Culture', 'Hiking', 'Let''s Travel and Rock', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Jacqui', 'Spaldin', 'jspaldinf@imdb.com', 'ewq789', '07-Jun-1979', 'Female', 'Israel', 'Jinta', '545-582-4713', 'Northern Sotho', null, null, 'Art', null, null, 'Come and Travel with me', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Elspeth', 'Spybey', 'espybeyg@cbsnews.com', 'fgd745', '01-Oct-1959', 'Male', 'United Kingdom', 'Terpsith?a', '310-233-6535', 'French', null, 'Dhivehi', 'Entertaiment', null, 'Nature', 'Let''s Travel and Rock', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Liza', 'Eames', 'leamesh@istockphoto.com', 'ewq789', '02-Aug-1963', 'Male', 'United Kingdom', 'Guilherand-Granges', '344-861-6719', 'Bengali', 'Malayalam', 'Bulgarian', 'Nature', 'Shoping', 'Hiking', 'Come and explore my beatiful country', 'yes');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Inger', 'Fillgate', 'ifillgatei@ibm.com', 'zxd123', '29-Jan-2020', 'Male', 'Israel', 'Sampu?s', '157-834-3368', 'Romanian', null, 'Georgian', 'Art', null, 'Hiking', 'Come and Travel with me', 'no');
insert into LocalGuides (first_name, last_name, email, password, dateOfBirth, gender, country, city, phoneNumber, language1, language2, language3, travelStyle1, travelStyle2, travelStyle3, about, mail) values ('Garland', 'Breslane', 'gbreslanej@wordpress.com', 'zxd123', '31-Oct-2019', 'Female', 'Israel', 'Mosetse', '326-933-7907', 'Chinese', 'Indonesian', null, 'Adventure', 'Hiking', null, 'Come and explore my beatiful country', 'no');
